# Generated by Django 4.1.3 on 2022-11-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField(blank=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('app_secret_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField(blank=True, null=True)),
                ('urls', models.URLField(blank=True, max_length=255)),
                ('http_methods', models.CharField(blank=True, max_length=255)),
                ('headers', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
